config/routes.rb
Rails.application.routes.draw do
  get '/' => 'index#index'

  get 'search' => 'search#index'
  get 'search/:emp_name' => 'search#show'

  get 'search_cr' => 'search_cr#index'
  get 'search_cr/:cr_name' => 'search_cr#show'

  resources :locations, :only => [:index, :show]
  resources :employees
  resources :conf_rooms
  get '/help' => 'help#index'
  root :to => 'home#index'

  mount PointlessFeedback::Engine, :at => '/feedback'

end

app/models/conf_room.rb
class ConfRoom < ActiveRecord::Base
  belongs_to :location

  def building 
    self.location.try(:location)
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  self.per_page = 25

  belongs_to :location

  validates :email,  uniqueness: true #, presence: true
  validates :first_name,  presence: true
  validates :last_name,   presence: true

  def building
    self.location.try(:location)
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :employees
  has_many :conf_rooms
  validates :location, presence: true, uniqueness: true

  def parent_location
    (self.parent ? Location.find(self.parent) : nil)
  end

  def children
    Location.where("parent = ?",self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conf_rooms_controller.rb
class ConfRoomsController < ApplicationController
  before_action :set_conf_room, only: [:show, :edit, :update, :destroy]
  before_action :load_locations, only: [:new, :edit, :create, :update]
  protect_from_forgery :except => [:update]

  # GET /conf_rooms
  # GET /conf_rooms.json
  def index
    @conf_rooms = ConfRoom.all.order("conf_room ASC")
  end

  # GET /conf_rooms/1
  # GET /conf_rooms/1.json
  def show
    @location = @conf_room.building
  end

  # GET /conf_rooms/new
  def new
    @conf_room = ConfRoom.new
  end

  # GET /conf_rooms/1/edit
  def edit
  end

  # POST /conf_rooms
  # POST /conf_rooms.json
  def create
    @conf_room = ConfRoom.new(conf_room_params)

    respond_to do |format|
      if @conf_room.save
        format.html { redirect_to @conf_room, notice: 'Conf room was successfully created.' }
        format.json { render :show, status: :created, location: @conf_room }
      else
        format.html { render :new }
        format.json { render json: @conf_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conf_rooms/1
  # PATCH/PUT /conf_rooms/1.json
  def update
    respond_to do |format|
      if @conf_room.update(conf_room_params)
        format.html { redirect_to @conf_room, notice: 'Conf room was successfully updated.' }
        format.json { render :show, status: :ok, location: @conf_room }
      else
        format.html { render :edit }
        format.json { render json: @conf_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conf_rooms/1
  # DELETE /conf_rooms/1.json
  def destroy
    @conf_room.destroy
    respond_to do |format|
      format.html { redirect_to conf_rooms_url, notice: 'Conf room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conf_room
      @conf_room = ConfRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conf_room_params
      params.require(:conf_room).permit(:conf_room, :location_id, :x_cord, :y_cord)
    end

    def load_locations
      @locations = Location.where(has_seats: 'Y').order('location').pluck(:location, :id)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :load_locations, only: [:new, :edit, :create, :update]
  protect_from_forgery :except => [:update]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.where("current_employee = 't'").page(params[:page]).order("first_name ASC, last_name ASC")
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @location = @employee.building
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @employee['current_employee'] = 't'
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    val = params.require(:employee).permit(:email, :current_employee, :first_name, :last_name, :location, :location_id, :x_cord, :y_cord, :phone_number, :extension)
    val['location'] = val['location_id'] ? Location.find_by(id: val['location_id']) : Location.find_by(id: val['location'])
    val
  end

  def load_locations
    @locations = Location.where(has_seats: 'Y').order('location').pluck(:location, :id)
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.where(has_seats: 'Y').order('location')
    respond_to do |format|
      format.html
      format.json { render :json => @locations }
    end
  end

  def show
    @location = Location.where(id: params[:id]).first
    @employees = Employee.where(location_id: params[:id]).where("current_employee = 't'").page(params[:page]).order("first_name ASC, last_name ASC")
    @employees2 = Employee.where(location_id: params[:id]).where("current_employee = 't'")
    @conf_rooms = ConfRoom.where(location_id: params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @location }
    end
  end

  def new
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def show
    name_lower = '%' +(params[:emp_name].downcase) + '%'
    @employees = Employee.where("current_employee = 't'").
        where("lower(first_name) like ? or lower(last_name) like ? or lower(email) like ? or (lower(first_name) || ' ' || lower(last_name) like ?)",
        name_lower, name_lower, name_lower, name_lower).page(params[:page]).order("first_name ASC, last_name ASC")
    @conf_rooms = ConfRoom.where("lower(conf_room) like ?", name_lower).order("conf_room ASC")
    if !@employees.many? && !@employees.empty? && @conf_rooms.empty?
        redirect_to controller: 'employees', action: 'show', id: @employees.first
    end
    if !@conf_rooms.many? && !@conf_rooms.empty? && @employees.empty?
        redirect_to controller: 'conf_rooms', action: 'show', id: @conf_rooms.first
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conf_rooms_helper.rb
module ConfRoomsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/search_cr_helper.rb
module SearchCrHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/conf_rooms/_form.html.erb
<%= form_for(@conf_room) do |f| %>
  <% if @conf_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conf_room.errors.count, "error") %> prohibited this conf_room from being saved:</h2>

      <ul>
      <% @conf_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conf_room %><br>
    <%= f.text_field :conf_room %>
  </div>
  <div class="field">
    <%= f.label :building, for: 'location_selector' %><br>
    <%= select(:conf_room, "location_id", @locations, {:include_blank => ''}, {id: 'location_selector'} ) %>
  </div>
  <div class="field">
    <%= f.label :x_cord, for: 'x_cord' %><br>
    <%= f.number_field :x_cord, id: 'x_cord', readonly: 'true' %>
  </div>
  <div class="field">
    <%= f.label :y_cord, for: 'y_cord' %><br>
    <%= f.number_field :y_cord, id: 'y_cord', readonly: 'true' %>
  </div>
  <div class="actions">
    <%= f.submit 'Update Conf Room', :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/conf_rooms/edit.html.erb
<h1>Editing Conf Room</h1>

<div class="conf_room_info">
<%= render 'form' %>
</div>

<div class="map" id="map_edit">
  <%- location = @conf_room.location -%>
  <%- if location %>
  <a href="/locations/<%= location.id %>"><%= image_tag location.image %></a>
    <%- if location.orientation %>
    <span class="compass_rose" style="transform: rotate(<%= location.orientation %>deg); display:inline-block">
      <%= image_tag 'compass_wind_rose-192.png' %></span>
    <%- else %>
    <span class="compass_rose" style="display:inline-block">
      <%= image_tag 'compass_wind_rose-192.png' %></span>
    <script>$('.compass_rose').hide()</script>
    <% end %>
  <div class="map_dot" style="top: <%= @conf_room.y_cord.to_i - 12 %>px; left: <%= @conf_room.x_cord.to_i - 12 %>px;">
    <img src="/images/red_circle.png" alt="<%= @conf_room.conf_room %>"/>
  </div>
  <%- else %>
  <a href="/locations/0"><%= image_tag 'unknown.png' %></a>
  <span class="compass_rose" style="display:inline-block">
    <%= image_tag 'compass_wind_rose-192.png' %></span>
  <div class="map_dot" style="top: 0px; left: 0px; display: none;">
    <img src="/images/red_circle.png" alt="<%= @conf_room.conf_room %>"/>
  </div>
  <script>$('.compass_rose').hide()</script>
  <% end %>
</div>

<div class="footar_nav">
<%= link_to '<button type="button" class="btn btn-primary">Back</button>'.html_safe, @conf_room %>
</div>

app/views/conf_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conference Room Directory</h1>

<table class="directory-listing">
  <thead>
    <tr>
      <th>Conf Room</th>
      <th>Building</th>
    </tr>
  </thead>

  <tbody>
    <% @conf_rooms.each do |conf_room| %>
      <tr>
        <td><%= link_to conf_room.conf_room, conf_room %></td>
        <td><%= link_to conf_room.building,  conf_room %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conf Room', new_conf_room_path %>

app/views/conf_rooms/new.html.erb
<h1>New Conf Room</h1>

<div class="conf_room_info">
<%= render 'form' %>
</div>

<div class="map" id="map_edit">
  <a href="/locations/0"><%= image_tag 'unknown.png' %></a>
  <span class="compass_rose" style="display:inline-block">
    <%= image_tag 'compass_wind_rose-192.png' %></span>
  <div class="map_dot" style="top: 0px; left: 0px; display: none;">
    <img src="/images/red_circle.png" alt=""/>
  </div>
</div>
<script>$('.compass_rose').hide()</script>

<div class="footar_nav">
<%= link_to '<button type="button" class="btn btn-primary">Back</button>'.html_safe, conf_rooms_path %>
</div>

app/views/conf_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<div id="info">
<div class="conf_room_info">
  <p>
    <strong>Conference Room:</strong>
    <input v-if="editMode" v-model="conf_room.conf_room"/>
    <span v-else>{{conf_room.conf_room}}</span>
  </p>

  <p>
    <strong>Building:</strong>
    <select v-if="editMode" v-model="conf_room.location" id="conf_room.location" @change="updateMap">
        <option v-for="location in locations" v-bind:value="location.value">
            {{ location.text }}
        </option>
    </select>
    <span v-else>{{conf_room.building}}</span>
  </p>

  <p v-if="editMode">
    <strong>X:</strong>
    <span>{{conf_room.x_cord}}</span>
  </p>
  <p v-if="editMode">
    <strong>Y:</strong>
    <span>{{conf_room.y_cord}}</span>
  </p>

  <p>
    <button v-if="editMode" type="button" class="btn btn-primary" @click="updateConfRoom">Save</button>
    <button v-else type="button" class="btn btn-primary" @click="editMode = true">Edit</button>
  </p>
</div>

<div class="map" id="map">
  <%- location = @conf_room.location -%>
  <% if location %>
  <a href="/locations/<%= location.id %>" @click="maphandler" ><img src='/assets/<%= location.image %>' v-bind:src="map_images[conf_room.location]"/></a>
  <% if location.orientation %>
    <span class="compass_rose" style="transform: rotate(<%= location.orientation %>deg); display:inline-block">
      <%= image_tag 'compass_wind_rose-192.png' %></span>
  <% end %>
    <% if @conf_room.x_cord || @conf_room.y_cord %>
    <div class="map_dot" v-bind:style="{left: conf_room.x_cord + 'px', top: conf_room.y_cord + 'px'}" v-if="conf_room.x_cord > 0 && conf_room.y_cord > 0">
      <img src="/images/red_circle.png" alt="<%= @conf_room.conf_room %>" title="<%= @conf_room.conf_room %>"/>
    </div>
    <% end %>
  <% end %>
</div>
</div>

<div class="footar_nav">
<%= link_to '<button type="button" class="btn btn-primary">Back</button>'.html_safe, conf_rooms_path %>
</div>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :current_employee %><br>
    <%= f.check_box :current_employee %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :building %><br>
    <%= f.select("location_id", @locations, {:include_blank => ' (choose a location) '}, {id: 'location_selector'} ) %>
  </div>
  <div class="field">
    <%= f.label :x_cord %><br>
    <%= f.number_field :x_cord, id: 'x_cord', readonly: 'true' %>
  </div>
  <div class="field">
    <%= f.label :y_cord %><br>
    <%= f.number_field :y_cord, id: 'y_cord', readonly: 'true' %>
  </div>
  <div class="actions">
    <%= f.submit 'Update Employee', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<div class="employee_info">
<%= render 'form' %>
</div>

<div class="map" id="map_edit">
  <%- location = @employee.location -%>
  <%- if location %>
  <a href="/locations/<%= location.id %>"><%= image_tag location.image %></a>
    <%- if location.orientation %>
    <span class="compass_rose" style="transform: rotate(<%= location.orientation %>deg); display:inline-block">
      <%= image_tag 'compass_wind_rose-192.png' %></span>
    <%- else %>
    <span class="compass_rose" style="display:inline-block">
      <%= image_tag 'compass_wind_rose-192.png' %></span>
    <script>$('.compass_rose').hide()</script>
    <% end %>
  <div class="map_dot" style="top: <%= @employee.y_cord.to_i - 12 %>px; left: <%= @employee.x_cord.to_i - 12 %>px;">
    <img src="/images/red_circle.png" alt="<%= @employee.first_name %> <%= @employee.last_name %>"/>
  </div>
  <%- else %>
  <a href="/locations/0"><%= image_tag 'unknown.png' %></a>
  <span class="compass_rose" style="display:inline-block">
    <%= image_tag 'compass_wind_rose-192.png' %></span>
  <div class="map_dot" style="top: 0px; left: 0px; display: none;">
    <img src="/images/red_circle.png" alt="<%= @employee.first_name %> <%= @employee.last_name %>"/>
  </div>
  <script>$('.compass_rose').hide()</script>
  <% end %>
</div>

<div class="footar_nav">
<%= link_to '<button type="button" class="btn btn-primary">Back</button>'.html_safe, @employee %>
</div>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Directory</h1>
<%= will_paginate @employees %>
<br/>
<table class="directory-listing">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Building</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.first_name, employee %></td>
        <td><%= link_to employee.last_name,  employee %></td>
        <td><%= employee.building %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>
<%= will_paginate @employees %><br/>
<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<div class="employee_info">
<%= render 'form' %>
</div>

<div class="map" id="map_edit">
  <a href="/locations/0"><%= image_tag 'unknown.png' %></a>
  <span class="compass_rose" style="display:inline-block">
    <%= image_tag 'compass_wind_rose-192.png' %></span>
  <div class="map_dot" style="top: 0px; left: 0px; display: none;">
    <img src="/images/red_circle.png" alt=""/>
  </div>
</div>
<script>$('.compass_rose').hide()</script>

<div class="footar_nav">
<%= link_to '<button type="button" class="btn btn-primary">Back</button>'.html_safe, employees_path %>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<div id="info">
<div class="employee_info" id="employee_info">
  <p>
    <strong>First name:</strong>
    <input v-if="editMode" v-model="employee.first_name"/>
    <span v-else>{{employee.first_name}}</span>
  </p>

  <p>
    <strong>Last name:</strong>
    <input v-if="editMode" v-model="employee.last_name"/>
    <span v-else>{{employee.last_name}}</span>
  </p>

  <p>
    <strong>Current employee:</strong>
    <span @click="employeeStatus" style="cursor:default">{{employee_status}}</span>
  </p>

  <p>
    <strong>Building:</strong>
    <select v-if="editMode" v-model="employee.location" id="employee.location" @change="updateMap">
        <option v-for="location in locations" v-bind:value="location.value">
            {{ location.text }}
        </option>
    </select>
    <span v-else>{{employee.building}}</span>
  </p>

  <p>
    <strong>Telephone:</strong>
    <input v-if="editMode" v-model="employee.phone_number"/>
    <span v-else>{{employee.phone_number}}</span>
  </p>

  <p>
    <strong>Extension:</strong>
    <input v-if="editMode" v-model="employee.extension"/>
    <span v-else>{{employee.extension}}</span>
  </p>

  <p>
    <strong>Email:</strong>
    <input v-if="editMode" v-model="employee.email"/>
    <span v-else>{{employee.email}}</span>
  </p>

  <p v-if="editMode">
    <strong>X:</strong>
    <span>{{employee.x_cord}}</span>
  </p>
  <p v-if="editMode">
    <strong>Y:</strong>
    <span>{{employee.y_cord}}</span>
  </p>

  <p>
    <button v-if="editMode" type="button" class="btn btn-primary" @click="updateEmployee">Save</button>
    <button v-else type="button" class="btn btn-primary" @click="editMode = true">Edit</button>
  </p>
</div>

<div class="map" id="map">
  <%- location = @employee.location -%>
  <% if location %>
  <a href="/locations/<%= location.id %>" @click="maphandler" v-bind:href="'/locations/'+employee.location"><img src="/assets/<%= location.image %>" v-bind:src="map_images[employee.location]" /></a>
  <% if location.orientation %>
    <span class="compass_rose" style="transform: rotate(<%= location.orientation %>deg); display:inline-block">
      <%= image_tag 'compass_wind_rose-192.png' %></span>
  <% end %>
    <% if @employee.x_cord || @employee.y_cord %>
    <div class="map_dot" v-bind:style="{left: employee.x_cord + 'px', top: employee.y_cord + 'px'}" v-if="employee.x_cord > 0 && employee.y_cord > 0">
      <img src="/images/red_circle.png" alt="<%= @employee.first_name %> <%= @employee.last_name %>" title="<%= @employee.first_name %> <%= @employee.last_name %>"/>
    </div>
    <% end %>
  <% end %>
</div>
</div>

<div class="footar_nav">
  <%= link_to '<button type="button" class="btn btn-primary">Back</button>'.html_safe, employees_path %>
</div>

app/views/help/index.html.erb
<h1> Welcome to the Find Me Help Center</h1>

<p>If you are looking for the desk location of a specific employee, their email address, or extension – select <a href="#employee">Employee Finder</a>.</p>

<p>Looking for the location of a conference room?  The <a href="#conf_rm">Conference Room Directory</a> can help you find it.</p>

<p>Know where someone sits but don’t remember their name? Or forget which conference room is which? If you know where within the building the person or room is located,
the <a href="#building">Building Directory</a> will help you find the person or room you are looking for.</p>

<h2 id="employee" class="navpoint">Employee Finder</h2>

<p>To find the desk location of an employee, begin by entering all or part of their name in the field Find by Employee name.</p>
<ul>
<li>All matching results will be returned, alphabetical by first name.</li>
<li>The results will be listed with the first and last name of the employee, and their building.  If applicable, the floor number will also appear.</li>
<li>To select an employee, click on their first or last name.</li>
<li>If only one result matches the entered criteria, the page with that employee’s location information will automatically load.</li>
</ul>


<h2 id="conf_rm" class="navpoint">Conference Room Directory</h2>

<ul>
<li>To find the desk location of a conference room, begin by entering all or part of the name in the field Find by Conference Room name.</li>
</ul>

<p style="margin-left: 20px; text-transform:uppercase;">or</p>

<ul>
<li>From the Conference Room Directory tab, select any room by name.  The page will list which building and floor the conference room is in, and the map will show the location on the floor.</li>
</ul>

<h2 id="building" class="navpoint">Building Directory</h2>

<ul>
<li>Select a building &amp; floor and the map will display showing the conference rooms
on the floor as well as the location of employees.</li>
<li>Hovering your mouse pointer over a dot on the map will display the name of the employee (red dot) or conference room (green dot) at that particular location.</li>
<li>If you want to know who sits in a general area of a building/floor, select the location on the map and it will display a list of those in the area and dots will show their location in that area.</li>
</ul>

<h2>Editing Employees &amp; Locations <span style='font-weight:normal;font-size:12pt;color:red'>&lt;permission based?&gt;</span></h2>

<h3>Add a new employee</h3>

<p>From the Employee Directory, select the link 'New Employee'.</p>

<ul>
<li>Enter their Email address</li>
<li>Select the box for 'current employee' if they are a current employee</li>
<li>Enter First name</li>
<li>Enter Last name</li>
<li>Select building and floor</li>
<li>Click their desk location on the map to populate the X and Y coordinates.</li>
<li>Click 'Create Employee'</li>
</ul>

<h3>Updating employee information or location</h3>

<ul>
<li>Locate the employee in the directory, and select 'Edit'.</li>
<li>Edit the fields accordingly for any name or email address changes.</li>
<li>For location changes, select the new location on the floor to move their dot, or select a new building &amp; floor and click the map location of their new desk to move the dot.</li>
<li>Click 'Update Employee'.</li>
</ul>

<h3>To remove an employee from a directory</h3>

<p>Locate the employee in the directory, and select 'Edit'. Uncheck the 'Current employee' box, and then Update Employee.</p>

<p class="page_bottom"></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Employee Finder</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" style="border: 0">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <img src="/assets/FindMeSmall.png" class="logo"/>
          <!-- <a class="navbar-brand" href="/">MSTS Employee Finder</a> -->
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/employees">Employee Directory</a></li>
            <li><a href="/conf_rooms">Conference Room Directory</a></li>
            <li><a href="/locations">Building Directory</a></li>
            <!-- <li><a href="/feedback">Feedback</a></li> -->
            <!-- <li><a href="/help">Help</a></li> -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="margin_left">
            <form method="GET" action="/search/" id="employee_search">
                <input id="emp_name" name="search_term" value="<%= params[:emp_name] %>"/>
                <button id="find_emp">Find 'Em!</button>
            </form>
        </div>
        <hr/>
        <div class="margin_left">
            <%= yield %>
        </div>
    </div><!-- /.container -->


  </body>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag params[:controller] %>
</html>